export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  STUDENT_SEARCH: '/student/search',
  STUDENT_PROPERTY: '/student/property/:id',
  STUDENT_VERIFICATION: '/student/verification',
  STUDENT_MY_STAY: '/student/my-stay',
  STUDENT_REQUESTS: '/student/requests',
  STUDENT_SAVED: '/student/saved',
  OWNER_DASHBOARD: '/owner/dashboard',
  OWNER_LISTINGS: '/owner/listings',
  OWNER_ADD_PROPERTY: '/owner/add-property',
  OWNER_TENANTS: '/owner/tenants',
  OWNER_PAYMENTS: '/owner/payments',
  OWNER_ANALYTICS: '/owner/analytics',
  OWNER_EDIT_LISTING: '/owner/listings/:id/edit',
  OWNER_VERIFICATION: '/owner/verification',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_VERIFY_ACCOUNTS: '/admin/verify-accounts',
  ADMIN_VERIFY_OWNERS: '/admin/verify-owners',
  ADMIN_APPROVE_LISTINGS: '/admin/approve-listings',
  ADMIN_LISTING_DETAIL: '/admin/listings/:id',
  ADMIN_MANAGE_USERS: '/admin/manage-users',
  ADMIN_MANAGE_TENANTS: '/admin/manage-tenants',
  ADMIN_AUDIT_LOG: '/admin/audit-log',
  ADMIN_MODERATE: '/admin/moderate',
};

/** Default landing page per role after login */
export const ROLE_HOME = {
  student: ROUTES.STUDENT_SEARCH,
  owner: ROUTES.OWNER_DASHBOARD,
  admin: ROUTES.ADMIN_DASHBOARD,
};
